### ISSUE TITLE
Re: Reddit Post - New HAL Issue with audio playback

### ISSUE THREAD

**Issue by garbochii** [ChapelR/harlowe-audio#29]
[Stories.zip](https://github.com/ChapelR/harlowe-audio/files/4866026/Stories.zip)

Thank you so much!

**Comment by ChapelR** [comment]
There are two problems. The first is the main one. Take a look at this:
![](https://i.imgur.com/YJ8aitB.jpg)
Your files are not named what you think they are. By default, Windows (I assume this is Windows because of this) hides file extensions from you. If you want to do any development work, you're gonna need those on. Fortunately, it's easy to do right in the folder `View` menu.

You can see the option on the far right below&mdash;I have it checked.
![](https://i.imgur.com/IrommjD.jpg)

The other issue is that your folder is called `Audio`, but in `HAL.tracks` it's called `audio`. These should match case. Windows is not case sensitive, but literally every other system on the planet is, and it will be when you publish it to the web as well. I recommend making everything lowercase.

So, to fix the issue:
- Turn on file extensions in Windows.
- Fix the file names.
- Change the `Audio` folder name to `audio`.

Here's the fixed file:
[story.zip](https://github.com/ChapelR/harlowe-audio/files/4866914/story.zip)

I'm closing this issue but feel free to comment with further questions. I will drop you a line on Reddit too to make sure you see this.

**Comment by garbochii** [comment]
Thank you so much! These are errors that seem really obvious in hindsight. Thank you for the time you took to help me out. I really appreciate it!
