### ISSUE TITLE
Synchronous looping

### ISSUE THREAD

**Issue by Firky** [ChapelR/harlowe-audio#34]
Hello. 
This HAL thing is really excellent. 
I'm a game composition teacher, not a coder, I'm afraid. 
For the past 7 or so years, I've been using Twine 1.4.2 with a version of this that I modified. https://www.glorioustrainwrecks.com/node/5061 I basically made multiple musical files of precisely the same length loop (synchronously) at zero volume, then students could turn stems on and off with fades. 
The playback (in at least Firefox and Chrome) was synchronous for ages. I had to add a preloading passage 2 years ago, or so, but the it was perfect again. Now, it's not. 
I'm trying various things. 
I know it's possible for browsers to loop stuff in line because of this. https://goodbyevolcanohigh.com/
The js is way over my head. https://goodbyevolcanohigh.com/main.0f5644a3.js
I haven't used Twine 2 much before, but I got Hal working. I can loop 2 musical files on one passage, but they're out of alignment. 
I've tried the preloading macros, which are working, but the files are not playing synchronously. 
I also successfully looped 2 files as a group, but they're not synchronous. 
Students really appreciate this assignment. It's super sad I can't figure out how to fix it. 
Do you have any suggestions? I'm aware it may be outside the scope of HAL, but I'd just love to get this working again for my students. 
Thanks for your time!
Meg

**Comment by Firky** [comment]
Also, I just noticed that these files are aligned in Chrome ... (I was using Firefox because gapless looping is better.) This is a good step forward.

**Comment by ChapelR** [comment]
I would love to help more but I am currently swamped. What you're looking for is called the Web Audio API. HAL uses the `HTMLMediaElements` API, which is incapable of seemless and gapless playback. Even if it sounds close on some browsers, you can't really use HAL for this sort of playback where multiple tracks need to align accurately. 

I used to maintain a library that was a bridge between an audio library called Howler and Harlowe. I can't recommend using my code for that anymore because it's years old now and probably doesn't work very well, but it is possible to get Howler working in Harlowe and it does use the Web Audio API. 

If I were to make a HAL 3 (I have no such plans, I should stress) I would move to that API myself for better, more accurate audio playback. My strong recommendation would be to attempt to get Howler or another audio library working in Harlowe, but if you can't (Harlowe is a PITA to work with with outside code) you might try to implement the API yourself. Loading, playing, and stopping tracks is not particularly difficult with it, so if that's all you need, then you can avoid trying to get a library to cooperate.

**Comment by Firky** [comment]
Thanks for the reply! One of my amazing composition students used howler as a start and has rewritten macros. Incredibly, it seems to work on all browsers and with a seamless loop. It has a few idiosyncrasies, like it wouldn't work until the second time you played a Twine (due to caching) but he fixed that too. I believe he got the idea of using groups from HAL. Let me know if it's of interest sometime. Keen to share knowledge.

**Comment by ChapelR** [comment]
Seems like you've got an A+ student on your hands! I'm glad everything worked out, only sorry I couldn't be of more help myself.
