### ISSUE TITLE
Having issue with (track:) macro

### ISSUE THREAD

**Issue by sparklebug** [ChapelR/harlowe-audio#48]
The track macro isn't working I'm using Harlowe 3.3.3

This is the message I’m getting
This is a call to a nonexistent or misspelled macro. This will cause an error.

**Comment by ChapelR** [comment]
That's not a run-time error message. Does it work when you play/test the game? It's normal for it to show as a non-defined macro when editing as noted in the docs.

![Capture](https://user-images.githubusercontent.com/25143560/192278224-77d69971-167b-4dfd-9e94-766b67b44ad1.JPG)

Make sure you're using the latest release either way.

**Comment by honzaflash** [comment]
The whole thing was broken for me in Harlowe 3.3.x - no sidebar, macros `masteraudio` and `track` caused errors (when actually run)

After switching back to 3.2.3 it works alright again.

If you want to try testing it for yourself the story is available [here](https://github.com/honzaflash/dvzka/blob/main/dvz-cernobyl/cernobyl.html) (only it's my custom split "format" so you need to paste the styles from css into the html if you want the style... Shouldn't be necessary for testing this).

Hope that can help

EDIT: ~I just realized I am not sure what version of HAL is in there, whoops~ There is HAL v2.2.1 in there so that is probably the issue :)
Yup, the new version fixes the problems, sorry for spam 😁

**Comment by ChapelR** [comment]
Np glad you got it working.
