### ISSUE TITLE
Chain one track after another

### ISSUE THREAD

**Issue by peastman** [ChapelR/harlowe-audio#7]
I'm trying to do something that seems like it should be simple, but I don't see any documented way to do it.  At one point in my game (call it "point A"), I want it to start playing a track.  Then at a later point ("point B"), I want to start playing another track.  But it's possible the first track won't yet have finished.  In that case, I don't want to interrupt it.  It should finish playing the first track, then start the second track when it reaches the end.  But if the first track ends before point B, the second track should not start until the player reaches point B.

Is this possible to do?

**Comment by ChapelR** [comment]
This is possible but not super simple. I'll get back to you in a few hours with code.

**Comment by peastman** [comment]
Thanks!  I did manage to figure out a way of doing it.  This may not be the cleanest solution, but it seems to work.

```html
<script>
function playTrack() {
  if (A.track('track1').isPlaying())
    setTimeout(playTrack, 50);
  else
    A.track('track2').play();
}
playTrack();
</script>
```

It just keeps checking every 50 ms to see whether the first track has finished yet.

**Comment by ChapelR** [comment]
The `:stop` event is a much safer and reliable way to do this. I haven't had a chance to test it, so it's possible the following code contains errors, but the general idea is:
```javascript
// place in a <script> in the passage where you want "songB" to start
if (A.track('songA').isPlaying()) {
    A.track('songA').$el.one(':stop', function () {
        // play the song when this one ends
        A.track('songB').play();
    });
} else {
    // play the song
    A.track('songB').play();
}
```
I'll also have an update to fix the `controls.show` option bug soonish, and I'll test to make sure this works the way it should too. Expect that update by tomorrow at the latest.

The track events are not well-documented, so I'll be addressing that in a future update as well, since using an interval (or recursive timeout) instead isn't a good idea, but the docs don't really tell you there are better options.

**Comment by ChapelR** [comment]
I tested the this code and it worked for me. Also added a [bit about the events to the docs](https://hal.twinelab.net/#/?id=events) (just a start for now). Let me know if the issue is solved and I'll close this.

**Comment by peastman** [comment]
Thanks!  The events look very useful.
